
version: '2'

services:
  ace_database:
    image: ace_database:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true